CREATE TABLE `users` (
	`id` text PRIMARY KEY NOT NULL,
	`display_name` text,
	`target_language` text,
	`native_language` text,
	`self_assessed_level` text,
	`placement_level` text,
	`current_level` text,
	`goal_domain` text,
	`target_days` integer DEFAULT 30,
	`minutes_per_day` integer DEFAULT 30,
	`days_per_week` integer DEFAULT 5,
	`preferred_mode` text DEFAULT 'voice',
	`onboarding_complete` integer DEFAULT false,
	`baseline_captured` integer DEFAULT false,
	`created_at` text DEFAULT (datetime('now')),
	`updated_at` text DEFAULT (datetime('now'))
);
--> statement-breakpoint
CREATE TABLE `plans` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`language` text NOT NULL,
	`start_level` text NOT NULL,
	`target_level` text NOT NULL,
	`start_date` text NOT NULL,
	`end_date` text NOT NULL,
	`total_days` integer NOT NULL,
	`current_cycle_number` integer DEFAULT 1,
	`current_cycle_start_date` text,
	`focus_errors` text,
	`scaffolding_level` integer DEFAULT 3,
	`review_ratio` real DEFAULT 0.3,
	`status` text DEFAULT 'active',
	`created_at` text DEFAULT (datetime('now')),
	`updated_at` text DEFAULT (datetime('now')),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`plan_id` text,
	`session_type` text NOT NULL,
	`scenario_id` text,
	`scenario_variant` text,
	`mode` text DEFAULT 'voice',
	`started_at` text,
	`completed_at` text,
	`duration_minutes` integer,
	`speaking_time_seconds` integer,
	`transcript` text,
	`fluency_score` real,
	`accuracy_score` real,
	`comprehensibility_score` real,
	`task_success_score` real,
	`replay_score` real,
	`corrections_count` integer DEFAULT 0,
	`redo_attempted` integer DEFAULT false,
	`redo_successful` integer,
	`status` text DEFAULT 'in_progress',
	`current_phase` text,
	`created_at` text DEFAULT (datetime('now')),
	`updated_at` text DEFAULT (datetime('now')),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`plan_id`) REFERENCES `plans`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `error_journal_entries` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`session_id` text,
	`error_type` text NOT NULL,
	`subtype` text,
	`example_wrong` text NOT NULL,
	`corrected_version` text NOT NULL,
	`rule_hint` text,
	`context` text,
	`language` text NOT NULL,
	`recurrence_count` integer DEFAULT 1,
	`last_seen_at` text DEFAULT (datetime('now')),
	`mastery_score` real DEFAULT 0,
	`drill_templates` text,
	`priority_weight` real DEFAULT 1,
	`status` text DEFAULT 'active',
	`created_at` text DEFAULT (datetime('now')),
	`updated_at` text DEFAULT (datetime('now')),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `vocab_entries` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`session_id` text,
	`term` text NOT NULL,
	`translation` text,
	`language` text NOT NULL,
	`usage_status` text DEFAULT 'introduced',
	`example_sentence` text,
	`scenario_id` text,
	`cefr_level` text,
	`correct_use_count` integer DEFAULT 0,
	`incorrect_use_count` integer DEFAULT 0,
	`last_used_at` text,
	`priority_review` integer DEFAULT false,
	`mastery_score` real DEFAULT 0,
	`part_of_speech` text,
	`created_at` text DEFAULT (datetime('now')),
	`updated_at` text DEFAULT (datetime('now')),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `checkpoints` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`plan_id` text,
	`session_id` text,
	`checkpoint_type` text NOT NULL,
	`day_number` integer NOT NULL,
	`speaking_prompt_id` text,
	`writing_prompt_id` text,
	`speaking_transcript` text,
	`writing_response` text,
	`fluency_score` real,
	`accuracy_score` real,
	`comprehensibility_score` real,
	`task_success_score` real,
	`replay_score` real,
	`baseline_checkpoint_id` text,
	`fluency_change` real,
	`accuracy_change` real,
	`comprehensibility_change` real,
	`task_success_change` real,
	`replay_score_change` real,
	`improvements` text,
	`focus_areas` text,
	`plan_updated` integer DEFAULT false,
	`completed_at` text,
	`created_at` text DEFAULT (datetime('now')),
	`updated_at` text DEFAULT (datetime('now')),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`plan_id`) REFERENCES `plans`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `micro_reviews` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`content_type` text NOT NULL,
	`error_entry_id` text,
	`vocab_entry_id` text,
	`review_type` text NOT NULL,
	`prompt` text NOT NULL,
	`expected_answer` text,
	`scheduled_for` text NOT NULL,
	`due_date` text NOT NULL,
	`interval_days` integer DEFAULT 1,
	`ease_factor` real DEFAULT 2.5,
	`repetition_number` integer DEFAULT 0,
	`completed` integer DEFAULT false,
	`completed_at` text,
	`user_answer` text,
	`was_correct` integer,
	`priority` real DEFAULT 1,
	`created_at` text DEFAULT (datetime('now')),
	`updated_at` text DEFAULT (datetime('now')),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`error_entry_id`) REFERENCES `error_journal_entries`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`vocab_entry_id`) REFERENCES `vocab_entries`(`id`) ON UPDATE no action ON DELETE cascade
);
