CREATE TABLE `conversations` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`session_id` text,
	`title` text,
	`type` text DEFAULT 'session',
	`current_phase` text,
	`status` text DEFAULT 'active',
	`message_count` integer DEFAULT 0,
	`user_message_count` integer DEFAULT 0,
	`assistant_message_count` integer DEFAULT 0,
	`total_tokens` integer DEFAULT 0,
	`started_at` text DEFAULT (datetime('now')),
	`last_message_at` text,
	`completed_at` text,
	`created_at` text DEFAULT (datetime('now')),
	`updated_at` text DEFAULT (datetime('now')),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `messages` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`conversation_id` text NOT NULL,
	`role` text NOT NULL,
	`content` text NOT NULL,
	`audio_url` text,
	`transcribed_from` text,
	`session_phase` text,
	`token_count` integer,
	`model` text,
	`provider` text,
	`latency_ms` integer,
	`is_edited` integer DEFAULT false,
	`original_content` text,
	`sequence_number` integer NOT NULL,
	`created_at` text DEFAULT (datetime('now')),
	`updated_at` text DEFAULT (datetime('now')),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`conversation_id`) REFERENCES `conversations`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `memories` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`source_conversation_id` text,
	`source_message_id` text,
	`type` text NOT NULL,
	`category` text,
	`content` text NOT NULL,
	`key` text,
	`value` text,
	`language` text,
	`cefr_level` text,
	`importance` real DEFAULT 1,
	`access_count` integer DEFAULT 0,
	`last_accessed_at` text,
	`confidence` real DEFAULT 1,
	`status` text DEFAULT 'active',
	`superseded_by` text,
	`embedding` text,
	`created_at` text DEFAULT (datetime('now')),
	`updated_at` text DEFAULT (datetime('now')),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`source_conversation_id`) REFERENCES `conversations`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`source_message_id`) REFERENCES `messages`(`id`) ON UPDATE no action ON DELETE set null
);
